spring:
  profiles:
    group:
      local: # ?? ??
        - common
        - local_db
      prod: # ?? ??
        - common
        - deploy_db

---

# common part
spring:
  config:
    activate:
      on-profile: "common"

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: "local_db"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    root: info